drop database if exists Boysozoku;
create database Boysozoku;
use Boysozoku;

CREATE TABLE UTENTE(
  USERNAME VARCHAR(40) PRIMARY KEY,
    EMAIL VARCHAR(40) NOT NULL UNIQUE,
    INDIRIZZO VARCHAR(40),
    APPARTAMENTO VARCHAR(40),
    CITTA VARCHAR(40),
    STATO VARCHAR(40),
    CAP INT,
    PROPIC VARCHAR(255),
  PASSWORD_UTENTE  VARCHAR(40) NOT NULL
);

CREATE TABLE ORDINI(
  ID INT PRIMARY KEY AUTO_INCREMENT,
    DATA_ORDINE DATE NOT NULL,
    SPEDITO BOOLEAN NOT NULL,
    PREZZO_TOT DEC(7, 2) NOT NULL,
    USERNAME_UTENTE VARCHAR(40) NOT NULL REFERENCES UTENTE(USERNAME)
  ON UPDATE CASCADE
);

CREATE TABLE MOD_BUILD(
  ID INT PRIMARY KEY AUTO_INCREMENT,
    CONSOLE ENUM("GB", "GBA", "GBC") NOT NULL,
    TIPO ENUM("SCOCCA", "SCHERMO", "PULSANTI") NOT NULL,
    PREZZO DEC(7, 2) NOT NULL,
    DESCRIZIONE VARCHAR(200) NOT NULL
);

CREATE TABLE BUILD(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(40) NOT NULL,
    CONSOLE ENUM("GB", "GBA", "GBC") NOT NULL,
    FILE_BUILD VARCHAR(255),
    ID_SCOCCA INT,
    ID_SCHERMO INT,
    ID_PULSANTI INT,
    PREZZO DEC(7,2) NOT NULL,
    FOREIGN KEY (ID_SCOCCA) REFERENCES MOD_BUILD(ID),
    FOREIGN KEY (ID_SCHERMO) REFERENCES MOD_BUILD(ID),
    FOREIGN KEY (ID_PULSANTI) REFERENCES MOD_BUILD(ID)
);

CREATE TABLE BUILD_ORDINATE(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  ID_BUILD_ORDINATE INT NOT NULL REFERENCES BUILD(ID),
  UTENTE_ORDINE VARCHAR(40) NOT NULL REFERENCES UTENTE(USERNAME),
  DATA_ORDINE DATE NOT NULL,
  DA_MONTARE BOOLEAN NOT NULL
);

CREATE TABLE BUILD_CARRELLO(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  DA_MONTARE BOOLEAN NOT NULL,
  UTENTE_CARRELLO VARCHAR(40) NOT NULL REFERENCES UTENTE(USERNAME),
  ID_BUILD_CARRELLO INT NOT NULL REFERENCES BUILD(ID)
);

CREATE TABLE PUBBLICAZIONE(
  DATA_PUBBLICAZIONE DATE NOT NULL,
    LIKE_MESSI INT NOT NULL,
    USERNAME_PUBBLICAZIONE VARCHAR(40) NOT NULL,
    FOREIGN KEY (USERNAME_PUBBLICAZIONE) REFERENCES UTENTE(USERNAME),
    ID_BUILD_PUBBLICAZIONE INT NOT NULL,
    FOREIGN KEY (ID_BUILD_PUBBLICAZIONE) REFERENCES BUILD(ID)
);